fct.icon.256=/io/github/juicefries/fct/icons/FCT_256.png
fct.icon.512=/io/github/juicefries/fct/icons/FCT_512.png
fct.icon.1024=/io/github/juicefries/fct/icons/FCT_1024.png
fct.icon.16=/io/github/juicefries/fct/icons/icon_16.png
fct.icon.32=/io/github/juicefries/fct/icons/icon_32.png
fct.icon.64=/io/github/juicefries/fct/icons/icon_64.png
fct.icon=/io/github/juicefries/fct/icons/icon.png
fct.blank.image.64=/io/github/juicefries/fct/icons/blank.png