fct.font.jetbrains.mono.bold=/io/github/juicefries/fct/fonts/JetBrainsMono-Bold.ttf
fct.font.jetbrains.mono.bold.italic=/io/github/juicefries/fct/fonts/JetBrainsMono-Bold-Italic.ttf
fct.font.jetbrains.mono.italic=/io/github/juicefries/fct/fonts/JetBrainsMono-Italic.ttf
fct.font.jetbrains.mono.regular=/io/github/juicefries/fct/fonts/JetBrainsMono-Regular.ttf
fct.font.lxgw.wenkai.mono.gb.screen=/io/github/juicefries/fct/fonts/LXGWWenKaiMonoGBScreen.ttf
fct.font.source.han.sans.sc.regular=/io/github/juicefries/fct/fonts/SourceHanSansSC-Regular.otf
